apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: emottak-admin
  namespace: default
  labels:
    team: integrasjon
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 512Mi
  vault:
    enabled: true
    paths:
      - kvPath: oracle/data/dev/creds/emottak_q1-srvemottaknais
        mountPath: /secrets/emottak-admin/credentials
  webproxy: true
  ingresses:
    - "https://emottak-admin.nais.preprod.local"
  env:
    - name: CLIENT_ID
      value: 9c95e7d7-b603-4aeb-a2f6-678ef5259248
    - name: AADACCESSTOKEN_URL
      value: https://login.microsoftonline.com/navq.onmicrosoft.com/oauth2/token
    - name: AADDISCOVERY_URL
      value: https://login.microsoftonline.com/navq.onmicrosoft.com/.well-known/openid-configuration
    - name: JWT_ISSUER
      value: https://sts.windows.net/966ac572-f5b7-4bbe-aa88-c76419c0f851/
    - name: DATABASE_URL
      value: jdbc:oracle:thin:@a01dbfl033.adeo.no:1521/emottak_q1
    - name: DATABASE_PREFIX
      value: emottak_q1
    - name: ALLOWED_APP_IDS
      value: c35dd346-0d3d-4b68-b883-a324c0b1098d