apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: emottak-admin
  namespace: default
  labels:
    team: integrasjon
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi
  vault:
    enabled: true
    paths:
      - kvPath: oracle/data/dev/creds/emottak_q1-srvemottaknais
        mountPath: /secrets/emottak-admin/credentials
